### ISSUE TITLE
Make use of Rails Assets

### ISSUE THREAD

**Issue by dentarg** [Starkast/wikimum#26]
https://rails-assets.org/

> Rails Assets is the frictionless proxy between Bundler and Bower.
> It automatically converts the packaged components into gems that are easily droppable into your asset pipeline and stay up to date.

WDYT?

**Comment by jage** [comment]
Would be interesting to try out, but I'm not completely confident this will work in the long run (years). But as I said, lets try it out.

**Comment by dentarg** [comment]
Their Let's Encrypt powered SSL certificate wasn't renewed: https://github.com/tenex/rails-assets/issues/416

**Comment by dentarg** [comment]
https://github.com/tenex/rails-assets-sinatra

**Comment by dentarg** [comment]
https://bower.io/ now says

>...psst! While Bower is maintained, we recommend using Yarn and Vite for front-end projects. [Read how to migrate!](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)

Let's not do this.
