### ISSUE TITLE
Try Dependabot

### ISSUE THREAD

**Issue by dentarg** [Starkast/wikimum#86]
> Dependabot creates pull requests to keep your dependencies secure and up-to-date.

https://dependabot.com/
https://github.com/marketplace/dependabot

**Comment by dentarg** [comment]
Hmm... I can't find our repo when I picked the free plan, it sounds like it should work:

> Public repos and personal account repos are free

**Comment by dentarg** [comment]
Ah, I picked my personal account, let's see if I can change that...

**Comment by dentarg** [comment]
Yes

<img width="523" alt="screen shot 2018-08-19 at 17 39 45" src="https://user-images.githubusercontent.com/42626/44310461-eaa7e280-a3d6-11e8-8283-218d04356da4.png">

**Comment by dentarg** [comment]
After that I was asked to add the project at https://app.dependabot.com/accounts/Starkast/repos

<img width="524" alt="screen shot 2018-08-19 at 17 40 49" src="https://user-images.githubusercontent.com/42626/44310470-1aef8100-a3d7-11e8-9773-9d71e8ec69ca.png">

Added it without changing any settings

> Daily bumping enabled! We've also kicked off an initial bump now, so keep an eye out for pull requests.

**Comment by dentarg** [comment]
PRs created :-)

https://github.com/Starkast/wikimum/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies

**Comment by dentarg** [comment]
They all failed... looks like Dependabot doesn't handle [vendored gems](https://bundler.io/v1.16/bundle_package.html) at all? cc @greysteil

**Comment by greysteil** [comment]
Ah, yes, Dependabot won't update your `vendor` folder at the moment. Let me take a look at fixing that. Might take a couple of days but I don't see why we shouldn't be able to do this...

**Comment by dentarg** [comment]
Sweet, looking forward to testing it out! 

If this test goes well, I'm pretty sure we will try it out at work (@twingly) too :-)

**Comment by greysteil** [comment]
Oh awesome, well that's a good incentive for me to get vendoring working 🙂

**Comment by dentarg** [comment]
@greysteil did you get a chance working on it? we can beta test the feature if you want to :-)

**Comment by greysteil** [comment]
Hey, sorry, have been totally swamped. I still really want to get to this, though - I'll keep you posted!

**Comment by greysteil** [comment]
Hey @dentarg,

I've been trying to get to this for the last couple of days, but it's bigger than I thought and, realistically, I don't think I can get it done in the next couple of weeks.

I don't want to keep you waiting, so, have you seen our competitor, [Depfu](https://depfu.com/)? They're a bit smaller than Dependabot and don't have all of our features, but they're good people and I *think* they have support for vendoring (correct me here if I'm wrong, though). You might want to give them a try as an alternative?

Sorry not to be able to support your setup with Dependabot just yet. 😢

**Comment by dentarg** [comment]
@greysteil Thanks for letting us know. Haven't seen Depfu before, so thanks for bringing it to my attention. Feel free to ping us if/when Dependabot gets support for vendoring. :)

**Comment by dentarg** [comment]
We can follow this issue: https://github.com/dependabot/dependabot-core/issues/370

**Comment by dentarg** [comment]
I will uninstall Dependabot as Depfu (#100) states support for vendored gems

**Comment by dentarg** [comment]
>You're all set. A job has been queued to uninstall Dependabot

**Comment by dentarg** [comment]
I'm gonna try Dependabot again: https://github.com/marketplace/dependabot-preview

**Comment by dentarg** [comment]
I've installed "Dependabot Preview" for our org and granted access to this repo.

**Comment by dentarg** [comment]
Before you can sign in to https://app.dependabot.com

<img width="638" alt="Screenshot 2020-05-31 at 19 53 45" src="https://user-images.githubusercontent.com/42626/83359130-8cb07900-a378-11ea-8eac-aaf798a58a19.png">

**Comment by dentarg** [comment]
I clicked the "Bump now" button at https://app.dependabot.com/accounts/Starkast

> Bump triggered - keep an eye out for pull requests

**Comment by dentarg** [comment]
I wonder why not all PRs have been rebased with latest master: https://github.com/Starkast/wikimum/pulls

Maybe there's some limit involved

Just discovered the docs on how to configure Dependabot: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

**Comment by dentarg** [comment]
> I wonder why not all PRs have been rebased with latest master

GitHub supports says try with (the built-in) `dependabot` instead of `dependabot-preview`: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview

**Comment by dentarg** [comment]
https://github.blog/changelog/2020-09-23-dependabot-supports-vendoring-for-ruby-bundler It happened! 🎉

**Comment by greysteil** [comment]
Yes! Took a little more than a couple of days, but @jurre and the the Dependabot team got it done 🎉

**Comment by jurre** [comment]
FYI, you'll have to use the GH native version of Dependabot in order to use the feature, there should be a button to convert the project on your dashboard on dependabot.com

**Comment by dentarg** [comment]
@jurre Thanks, I knew I need to switch but thanks for letting me know about the button :)

**Comment by dentarg** [comment]
@jurre will the button create a PR like https://github.com/weppos/publicsuffix-ruby/pull/178 or when does that happen? :)

**Comment by jurre** [comment]
> @jurre will the button create a PR like [weppos/publicsuffix-ruby#178](https://github.com/weppos/publicsuffix-ruby/pull/178) or when does that happen? :)

Yep 👍

**Comment by dentarg** [comment]
Still getting PRs from @dependabot-preview: https://github.com/Starkast/wikimum/pull/212, https://github.com/Starkast/wikimum/pull/213

At https://github.com/Starkast/wikimum/settings/installations clicked `Configure` on "Dependabot Preview", arrived at https://github.com/organizations/Starkast/settings/installations/9380283 and clicked `Uninstall`

>Uninstall "Dependabot Preview"
>This will remove the app and revoke access to all resources.

> This action cannot be undone. Are you sure you want to uninstall this GitHub App from 1 repository?

> You're all set. A job has been queued to uninstall Dependabot Preview

Let's see what happens now. I'll just close the mentioned PRs (as I removed the vendoring workflow, they can't be merged as-is).

**Comment by greysteil** [comment]
If you've clicked uninstall, Dependabot Preview won't have any access to this repo to be able to create PRs. On the backend it's just a normal GitHub app, so uninstalling it removes all its permissions on the GitHub side.
